"""Chat API router with SSE streaming endpoint."""

import json
import logging
from collections.abc import AsyncGenerator
from typing import Optional

from fastapi import APIRouter
from fastapi.responses import StreamingResponse

from app.core.settings import get_settings
from app.schemas.chat import ChatRequest
from app.services.chat_service import ChatService

from langsmith import traceable

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/chat", tags=["chat"])

# Lazy-initialised singleton — avoids import-time dependency on API keys
chat_service: Optional[ChatService] = None


async def event_generator(
    messages: list,  # noqa: ANN401 — FastAPI dependency injection
    retrieval_mode: str = "auto",
    settings: dict | None = None,
    skip_intent: bool = False,
) -> AsyncGenerator[str, None]:
    """Yield SSE-formatted events from the chat service.

    Args:
        messages: List of ChatMessage dicts from the validated request.

    Yields:
        SSE ``data:`` lines, one per event (status/retrieval/token/error).
    """
    global chat_service
    if chat_service is None:
        chat_service = ChatService(get_settings())

    try:
        async for event_str in chat_service.stream_chat(messages, retrieval_mode, settings, skip_intent):
            yield f"data: {event_str}\n\n"
    except Exception:
        logger.exception("Error during SSE stream")
        yield f"data: {json.dumps({'type': 'error', 'error': 'Internal server error', 'done': True})}\n\n"

@traceable(name="chat_endpoint")
@router.post("")
async def chat_endpoint(request: ChatRequest) -> StreamingResponse:
    """Stream a chat response via Server-Sent Events.

    Accepts a ``ChatRequest`` JSON body and returns an SSE stream of
    multi-stage events generated by the ``ChatService``.

    **SSE format**:

    .. code-block::

        data: {"type":"status","node":"routing","label":"...","decision":{...}}\n\n
        data: {"type":"retrieval","source":"student_manual","chunks":[...]}\n\n
        data: {"type":"token","token":"Hello"}\n\n
        data: {"type":"token","token":"","done":true}\n\n

    On errors the stream produces a single error chunk:

    .. code-block::

        data: {"type":"error","error":"...","done":true}\n\n
    """
    return StreamingResponse(
        event_generator(request.messages, request.retrieval_mode, request.settings, request.skip_intent),
        media_type="text/event-stream",
    )


@router.get("")
async def chat_root() -> dict:
    """Chat root - placeholder response."""
    return {"message": "Chat API placeholder"}
